name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_traffic: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14 
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_gists: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          config_timezone: Europe/Warsaw
          config_padding: 10%
