name: Snake animation
on:
  schedule: [{cron: "0 */8 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  snake-anim:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: generate snake.svg
      - uses: Platane/snk/svg-only@v2
        with:
          filename: snake.svg
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
