name: Snake animation
on:
  schedule: [{cron: "0 */8 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  snake-anim:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: generate github-contribution-grid-snake.svg
      - uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
